# Generated by Django 5.1 on 2024-09-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_categories_task'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='categories',
            field=models.ManyToManyField(to='categories.categories'),
        ),
    ]
